version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    container_name: electromart-backend
    ports:
      - "8092:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/electromart
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:8092
    container_name: electromart-frontend
    ports:
      - "8091:80"
    depends_on:
      - backend
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: electromart-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  # --- MONITORING STACK START ---
  prometheus:
    image: prom/prometheus
    container_name: electromart-prometheus
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "8094:9090"
    networks:
      - app-network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: electromart-node-exporter
    ports:
      - "9100:9100"
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    container_name: electromart-grafana
    ports:
      - "8093:3000"
    networks:
      - app-network
    volumes:
      - grafana-storage:/var/lib/grafana
      # 1. Mount Dashboards Config
      - ../monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ../monitoring/grafana/provisioning/dashboards:/var/lib/grafana/dashboards
      # 2. Mount Datasources Config (THE NEW FIX)
      - ../monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
  grafana-storage: