---
- name: Install Docker & AWS CLI
  hosts: all       # <-- CHANGED from 'private' to 'all' to include Bastion
  become: yes      # Run as root (sudo)
  vars:
    ansible_ssh_pipelining: yes

  tasks:
    - name: Update Apt Cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Docker and AWS CLI
      apt:
        name:
          - docker.io
          - awscli
        state: present

    - name: Start and Enable Docker Service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add 'ubuntu' user to Docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
      # This allows us to run 'docker' commands without 'sudo' later